# Generated by Django 5.1.15 on 2026-09-23 06:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(db_index=True, verbose_name='action date')),
                ('action_type', models.CharField(choices=[('call', 'Call made'), ('message', 'Message sent'), ('visit', 'Visit made'), ('promise', 'Promise to pay'), ('not_found', 'Customer not reached'), ('agreement', 'Payment agreement')], max_length=20, verbose_name='action type')),
                ('outcome', models.CharField(choices=[('paid', 'Payment made'), ('promised', 'Promises to pay'), ('no_answer', 'No answer'), ('refused', 'Refuses to pay'), ('rescheduled', 'Reschedule contact'), ('other', 'Other')], default='other', max_length=20, verbose_name='outcome')),
                ('promised_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='promised amount')),
                ('promise_date', models.DateField(blank=True, null=True, verbose_name='promise date')),
                ('next_contact_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='next contact date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_actions', to='businesses.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'collection action',
                'verbose_name_plural': 'collection actions',
                'ordering': ['-performed_at'],
            },
        ),
    ]
