# Generated by Django 5.1.15 on 2026-09-23 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_actions', to=settings.AUTH_USER_MODEL, verbose_name='handled by'),
        ),
        migrations.AddIndex(
            model_name='collectionaction',
            index=models.Index(fields=['business', '-performed_at'], name='collections_busines_b842e9_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionaction',
            index=models.Index(fields=['user', '-performed_at'], name='collections_user_id_82e833_idx'),
        ),
    ]
