# Generated by Django 5.1.15 on 2026-09-23 06:13

import apps.core.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('trade_name', models.CharField(max_length=150, verbose_name='trade name')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='legal name')),
                ('tax_id', models.CharField(blank=True, max_length=13, validators=[apps.core.validators.validate_tax_id], verbose_name='RFC')),
                ('phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAMP', 'Campeche'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de Mexico'), ('COAH', 'Coahuila'), ('COL', 'Colima'), ('DGO', 'Durango'), ('MEX', 'Estado de Mexico'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MICH', 'Michoacan'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo Leon'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Queretaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosi'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAMS', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatan'), ('ZAC', 'Zacatecas')], max_length=5, verbose_name='state')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('interest_mode', models.CharField(choices=[('flat_on_principal', 'Flat interest on principal (rate x principal)'), ('simple_per_period', 'Simple interest per period (rate x principal x installments)'), ('no_interest', 'No interest')], default='flat_on_principal', max_length=20, verbose_name='interest mode')),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.4000'), help_text='Expressed as a ratio. 0.4000 = 40% (400 MXN per 1,000 MXN).', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='interest rate')),
                ('rate_period', models.CharField(choices=[('contract', 'For the whole contract term'), ('daily', 'Per day'), ('weekly', 'Per week'), ('biweekly', 'Per fortnight'), ('monthly', 'Per month')], default='contract', help_text='Contractual period the rate refers to. It must match the contract.', max_length=15, verbose_name='rate period')),
                ('payment_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly (every 15 days)'), ('monthly', 'Monthly'), ('custom', 'Custom (every N days)')], default='weekly', max_length=15, verbose_name='default payment frequency')),
                ('installment_count', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='default number of installments')),
                ('grace_days', models.PositiveIntegerField(default=0, help_text='Days after the due date before an installment counts as overdue.', verbose_name='grace days')),
                ('charges_late_fee', models.BooleanField(default=False, help_text='When off, the system never adds late charges. Turn it on only with a documented and authorized policy.', verbose_name='charges late fees')),
                ('late_fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Ratio applied to the overdue balance, per day past due.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='daily late fee rate')),
                ('allows_early_payoff', models.BooleanField(default=True, verbose_name='allows early payoff')),
                ('early_payoff_discount', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Ratio discounted from the UNEARNED interest. 0 = the full contractual balance is charged.', max_digits=7, verbose_name='early payoff discount')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'business',
                'verbose_name_plural': 'businesses',
                'ordering': ['trade_name'],
            },
        ),
    ]
