# Generated by Django 5.1.15 on 2026-09-23 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='business',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_businesses', to=settings.AUTH_USER_MODEL, verbose_name='person in charge'),
        ),
        migrations.AddField(
            model_name='business',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(condition=models.Q(('interest_rate__gte', 0)), name='business_rate_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='business',
            constraint=models.CheckConstraint(condition=models.Q(('installment_count__gte', 1)), name='business_min_one_installment'),
        ),
    ]
