# Generated by Django 5.1.15 on 2026-09-23 06:13

import apps.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('relationship', models.CharField(blank=True, max_length=80, verbose_name='relationship')),
                ('phone', models.CharField(max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
            ],
            options={
                'verbose_name': 'personal reference',
                'verbose_name_plural': 'personal references',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(blank=True, help_text='Internal identifier of the customer within the business.', max_length=20, verbose_name='code')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name(s)')),
                ('last_name', models.CharField(max_length=80, verbose_name='last name')),
                ('second_last_name', models.CharField(blank=True, max_length=80, verbose_name='second last name')),
                ('national_id', models.CharField(blank=True, max_length=18, validators=[apps.core.validators.validate_national_id], verbose_name='CURP')),
                ('tax_id', models.CharField(blank=True, max_length=13, validators=[apps.core.validators.validate_tax_id], verbose_name='RFC')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('phone', models.CharField(max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='primary phone')),
                ('alt_phone', models.CharField(blank=True, max_length=20, validators=[apps.core.validators.validate_phone], verbose_name='alternate phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('state', models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAMP', 'Campeche'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de Mexico'), ('COAH', 'Coahuila'), ('COL', 'Colima'), ('DGO', 'Durango'), ('MEX', 'Estado de Mexico'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MICH', 'Michoacan'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo Leon'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Queretaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosi'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAMS', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatan'), ('ZAC', 'Zacatecas')], max_length=5, verbose_name='state')),
                ('postal_code', models.CharField(blank=True, max_length=5, validators=[apps.core.validators.validate_postal_code], verbose_name='postal code')),
                ('occupation', models.CharField(blank=True, max_length=120, verbose_name='occupation')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('restricted', 'Restricted')], default='active', max_length=15, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='internal notes')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='businesses.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['last_name', 'second_last_name', 'first_name'],
            },
        ),
    ]
