# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(db_index=True, verbose_name='fecha de la gestion')),
                ('tipo', models.CharField(choices=[('llamada', 'Llamada realizada'), ('mensaje', 'Mensaje enviado'), ('visita', 'Visita realizada'), ('promesa', 'Promesa de pago'), ('no_localizado', 'Cliente no localizado'), ('acuerdo', 'Acuerdo de pago')], max_length=20, verbose_name='tipo de gestion')),
                ('resultado', models.CharField(choices=[('pago', 'Pago realizado'), ('promesa', 'Promete pagar'), ('sin_respuesta', 'Sin respuesta'), ('negativa', 'Se niega a pagar'), ('reagenda', 'Reagendar contacto'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='resultado')),
                ('monto_prometido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='monto prometido')),
                ('fecha_promesa', models.DateField(blank=True, null=True, verbose_name='fecha de la promesa')),
                ('proxima_fecha_contacto', models.DateField(blank=True, db_index=True, null=True, verbose_name='proxima fecha de contacto')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'gestion de cobranza',
                'verbose_name_plural': 'gestiones de cobranza',
                'ordering': ['-fecha'],
            },
        ),
    ]
