# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranza', '0002_initial'),
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestioncobranza',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='negocios.negocio', verbose_name='negocio'),
        ),
    ]
