# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranza', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gestioncobranza',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gestiones', to=settings.AUTH_USER_MODEL, verbose_name='gestionado por'),
        ),
        migrations.AddIndex(
            model_name='gestioncobranza',
            index=models.Index(fields=['negocio', '-fecha'], name='cobranza_ge_negocio_accd34_idx'),
        ),
        migrations.AddIndex(
            model_name='gestioncobranza',
            index=models.Index(fields=['usuario', '-fecha'], name='cobranza_ge_usuario_968833_idx'),
        ),
    ]
