# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('info', 'Informativa'), ('alerta', 'Alerta'), ('mora', 'Mora')], default='info', max_length=10, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=150, verbose_name='titulo')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='enlace')),
                ('leida', models.BooleanField(default=False, verbose_name='leida')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='negocios.negocio', verbose_name='negocio')),
            ],
            options={
                'verbose_name': 'notificacion',
                'verbose_name_plural': 'notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
    ]
