# Generated by Django 5.1.15 on 2026-09-22 15:53

import apps.core.validadores
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('codigo', models.CharField(blank=True, help_text='Identificador interno del cliente dentro del negocio.', max_length=20, verbose_name='codigo')),
                ('nombres', models.CharField(max_length=100, verbose_name='nombre(s)')),
                ('apellido_paterno', models.CharField(max_length=80, verbose_name='apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=80, verbose_name='apellido materno')),
                ('curp', models.CharField(blank=True, max_length=18, validators=[apps.core.validadores.validar_curp], verbose_name='CURP')),
                ('rfc', models.CharField(blank=True, max_length=13, validators=[apps.core.validadores.validar_rfc], verbose_name='RFC')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('telefono_principal', models.CharField(max_length=20, validators=[apps.core.validadores.validar_telefono], verbose_name='telefono principal')),
                ('telefono_alterno', models.CharField(blank=True, max_length=20, validators=[apps.core.validadores.validar_telefono], verbose_name='telefono alterno')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electronico')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='direccion')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('estado_republica', models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAMP', 'Campeche'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de Mexico'), ('COAH', 'Coahuila'), ('COL', 'Colima'), ('DGO', 'Durango'), ('MEX', 'Estado de Mexico'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MICH', 'Michoacan'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo Leon'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Queretaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosi'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAMS', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatan'), ('ZAC', 'Zacatecas')], max_length=5, verbose_name='estado')),
                ('codigo_postal', models.CharField(blank=True, max_length=5, validators=[apps.core.validadores.validar_codigo_postal], verbose_name='codigo postal')),
                ('ocupacion', models.CharField(blank=True, max_length=120, verbose_name='ocupacion o actividad economica')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('restringido', 'Restringido')], default='activo', max_length=15, verbose_name='estado')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones internas')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='ReferenciaPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('parentesco', models.CharField(blank=True, max_length=80, verbose_name='parentesco o relacion')),
                ('telefono', models.CharField(max_length=20, validators=[apps.core.validadores.validar_telefono], verbose_name='telefono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='direccion')),
            ],
            options={
                'verbose_name': 'referencia personal',
                'verbose_name_plural': 'referencias personales',
                'ordering': ['nombre'],
            },
        ),
    ]
