# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cobrador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'cobrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='cobrador asignado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='negocios.negocio', verbose_name='negocio'),
        ),
        migrations.AddField(
            model_name='referenciapersonal',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='clientes.cliente', verbose_name='cliente'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['negocio', 'estado'], name='clientes_cl_negocio_c995ae_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['telefono_principal'], name='clientes_cl_telefon_f992c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(condition=models.Q(('codigo', ''), _negated=True), fields=('negocio', 'codigo'), name='cliente_codigo_unico_por_negocio'),
        ),
    ]
