# Generated by Django 5.1.15 on 2026-09-23 06:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='allocated amount')),
                ('principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='principal')),
                ('interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='interest')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'payment allocation',
                'verbose_name_plural': 'payment allocations',
                'ordering': ['payment', 'installment__number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='reference')),
                ('paid_at', models.DateTimeField(db_index=True, verbose_name='payment date and time')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount received')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount allocated to installments')),
                ('overpayment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Only allowed with an explicit authorization when registering.', max_digits=12, verbose_name='unallocated overpayment')),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank transfer'), ('deposit', 'Deposit'), ('other', 'Other')], default='cash', max_length=15, verbose_name='payment method')),
                ('kind', models.CharField(choices=[('payment', 'Customer payment'), ('write_off', 'Authorized write-off / discount')], default='payment', max_length=15, verbose_name='kind')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('reversed', 'Reversed')], db_index=True, default='confirmed', max_length=12, verbose_name='status')),
                ('external_reference', models.CharField(blank=True, max_length=80, verbose_name='transaction reference')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('idempotency_key', models.CharField(blank=True, help_text='Prevents the same form from registering the payment twice.', max_length=64, verbose_name='idempotency key')),
                ('reversal_reason', models.CharField(blank=True, max_length=255, verbose_name='reversal reason')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='reversal date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='businesses.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-paid_at', '-id'],
            },
        ),
    ]
