# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('creditos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe aplicado')),
                ('capital', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='capital')),
                ('interes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='interes')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='creditos.cuota', verbose_name='cuota')),
            ],
            options={
                'verbose_name': 'aplicacion de pago',
                'verbose_name_plural': 'aplicaciones de pago',
                'ordering': ['pago', 'cuota__numero'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=30, unique=True, verbose_name='folio')),
                ('fecha', models.DateTimeField(db_index=True, verbose_name='fecha y hora del pago')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='importe recibido')),
                ('importe_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='importe aplicado a cuotas')),
                ('excedente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Solo se permite con autorizacion explicita al registrar el pago.', max_digits=12, verbose_name='excedente no aplicado')),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('deposito', 'Deposito'), ('otro', 'Otro')], default='efectivo', max_length=15, verbose_name='metodo de pago')),
                ('tipo', models.CharField(choices=[('pago', 'Pago del cliente'), ('condonacion', 'Condonacion / descuento autorizado')], default='pago', max_length=15, verbose_name='tipo')),
                ('estado', models.CharField(choices=[('confirmado', 'Confirmado'), ('reversado', 'Reversado')], db_index=True, default='confirmado', max_length=12, verbose_name='estado')),
                ('referencia', models.CharField(blank=True, max_length=80, verbose_name='referencia de la transaccion')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('clave_idempotencia', models.CharField(blank=True, help_text='Evita que un mismo formulario registre el pago dos veces.', max_length=64, verbose_name='clave de idempotencia')),
                ('motivo_reverso', models.CharField(blank=True, max_length=255, verbose_name='motivo del reverso')),
                ('reversado_en', models.DateTimeField(blank=True, null=True, verbose_name='fecha del reverso')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='clientes.cliente', verbose_name='cliente')),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
