# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creditos', '0002_initial'),
        ('negocios', '0002_initial'),
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cobrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_gestionados', to=settings.AUTH_USER_MODEL, verbose_name='cobrador'),
        ),
        migrations.AddField(
            model_name='pago',
            name='credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='creditos.credito', verbose_name='credito'),
        ),
        migrations.AddField(
            model_name='pago',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='negocios.negocio', verbose_name='negocio'),
        ),
        migrations.AddField(
            model_name='pago',
            name='recibido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='registrado por'),
        ),
        migrations.AddField(
            model_name='pago',
            name='reversado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_reversados', to=settings.AUTH_USER_MODEL, verbose_name='reversado por'),
        ),
        migrations.AddField(
            model_name='aplicacionpago',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='pagos.pago', verbose_name='pago'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['negocio', 'estado', '-fecha'], name='pagos_pago_negocio_345f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['credito', 'estado'], name='pagos_pago_credito_5e6e14_idx'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='pago_importe_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(condition=models.Q(('excedente__gte', 0)), name='pago_excedente_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.UniqueConstraint(condition=models.Q(('clave_idempotencia', ''), _negated=True), fields=('clave_idempotencia',), name='pago_clave_idempotencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='aplicacionpago',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='aplicacion_importe_positivo'),
        ),
    ]
