# Generated by Django 5.1.15 on 2026-09-22 16:03

import apps.usuarios.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
    ]
