# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('folio', models.CharField(editable=False, max_length=30, unique=True, verbose_name='folio')),
                ('fecha_solicitud', models.DateField(verbose_name='fecha de solicitud')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='fecha de aprobacion')),
                ('fecha_desembolso', models.DateField(blank=True, null=True, verbose_name='fecha de desembolso')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='capital prestado')),
                ('modalidad_interes', models.CharField(choices=[('fijo_capital', 'Interes fijo sobre el capital (tasa x capital)'), ('simple_periodo', 'Interes simple por periodo (tasa x capital x cuotas)'), ('sin_interes', 'Sin interes')], default='fijo_capital', max_length=20, verbose_name='modalidad de interes')),
                ('tasa_interes', models.DecimalField(decimal_places=4, default=Decimal('0.4000'), help_text='Tanto por uno congelado al aprobar el credito.', max_digits=7, verbose_name='tasa de interes aplicada')),
                ('periodo_tasa', models.CharField(choices=[('contrato', 'Por el plazo completo del contrato'), ('diario', 'Por dia'), ('semanal', 'Por semana'), ('quincenal', 'Por quincena'), ('mensual', 'Por mes')], default='contrato', max_length=15, verbose_name='periodo de la tasa')),
                ('interes_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='interes total')),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total a pagar')),
                ('frecuencia_pago', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal (cada 15 dias)'), ('mensual', 'Mensual'), ('personalizado', 'Personalizado (cada N dias)')], default='semanal', max_length=15, verbose_name='frecuencia de pago')),
                ('dias_personalizados', models.PositiveIntegerField(blank=True, help_text='Solo para frecuencia personalizada.', null=True, verbose_name='dias entre cuotas')),
                ('numero_cuotas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='numero de cuotas')),
                ('importe_cuota', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='importe de cada cuota')),
                ('fecha_primer_pago', models.DateField(verbose_name='fecha del primer pago')),
                ('fecha_vencimiento_final', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento final')),
                ('capital_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='capital pagado')),
                ('interes_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='interes pagado')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='saldo pendiente')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('pendiente_aprobacion', 'Pendiente de aprobacion'), ('aprobado', 'Aprobado'), ('desembolsado', 'Desembolsado'), ('activo', 'Activo'), ('en_mora', 'En mora'), ('liquidado', 'Liquidado'), ('cancelado', 'Cancelado'), ('reestructurado', 'Reestructurado')], db_index=True, default='borrador', max_length=25, verbose_name='estado')),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255, verbose_name='motivo de cancelacion')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos/%Y/%m/', verbose_name='contrato o documento')),
            ],
            options={
                'verbose_name': 'credito',
                'verbose_name_plural': 'creditos',
                'ordering': ['-fecha_solicitud', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='numero de cuota')),
                ('fecha_vencimiento', models.DateField(db_index=True, verbose_name='fecha de vencimiento')),
                ('importe_programado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='importe programado')),
                ('capital_programado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='capital programado')),
                ('interes_programado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='interes programado')),
                ('importe_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='importe pagado')),
                ('capital_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='capital pagado')),
                ('interes_pagado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='interes pagado')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], db_index=True, default='pendiente', max_length=12, verbose_name='estado')),
                ('fecha_liquidacion', models.DateField(blank=True, null=True, verbose_name='fecha de liquidacion')),
            ],
            options={
                'verbose_name': 'cuota',
                'verbose_name_plural': 'cuotas',
                'ordering': ['credito', 'numero'],
            },
        ),
    ]
