# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_initial'),
        ('creditos', '0001_initial'),
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='credito',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='credito',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por'),
        ),
        migrations.AddField(
            model_name='credito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='clientes.cliente', verbose_name='cliente'),
        ),
        migrations.AddField(
            model_name='credito',
            name='cobrador',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'cobrador'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='cobrador asignado'),
        ),
        migrations.AddField(
            model_name='credito',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='credito',
            name='credito_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reestructuraciones', to='creditos.credito', verbose_name='credito reestructurado'),
        ),
        migrations.AddField(
            model_name='credito',
            name='desembolsado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_desembolsados', to=settings.AUTH_USER_MODEL, verbose_name='desembolsado por'),
        ),
        migrations.AddField(
            model_name='credito',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creditos', to='negocios.negocio', verbose_name='negocio'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='creditos.credito', verbose_name='credito'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['negocio', 'estado'], name='creditos_cr_negocio_0ba397_idx'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['cliente', 'estado'], name='creditos_cr_cliente_0ed47f_idx'),
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['cobrador', 'estado'], name='creditos_cr_cobrado_62beff_idx'),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('capital__gt', 0)), name='credito_capital_positivo'),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('interes_total__gte', 0)), name='credito_interes_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('numero_cuotas__gte', 1)), name='credito_cuotas_min_1'),
        ),
        migrations.AddConstraint(
            model_name='credito',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__gte', 0)), name='credito_saldo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.UniqueConstraint(fields=('credito', 'numero'), name='cuota_numero_unico_por_credito'),
        ),
        migrations.AddConstraint(
            model_name='cuota',
            constraint=models.CheckConstraint(condition=models.Q(('importe_programado__gte', 0)), name='cuota_importe_no_negativo'),
        ),
    ]
