# Generated by Django 5.1.15 on 2026-09-22 15:53

import apps.core.validadores
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('nombre_comercial', models.CharField(max_length=150, verbose_name='nombre comercial')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='razon social')),
                ('rfc', models.CharField(blank=True, max_length=13, validators=[apps.core.validadores.validar_rfc], verbose_name='RFC')),
                ('telefono', models.CharField(blank=True, max_length=20, validators=[apps.core.validadores.validar_telefono], verbose_name='telefono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electronico')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='direccion')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('estado', models.CharField(blank=True, choices=[('AGS', 'Aguascalientes'), ('BC', 'Baja California'), ('BCS', 'Baja California Sur'), ('CAMP', 'Campeche'), ('CHIS', 'Chiapas'), ('CHIH', 'Chihuahua'), ('CDMX', 'Ciudad de Mexico'), ('COAH', 'Coahuila'), ('COL', 'Colima'), ('DGO', 'Durango'), ('MEX', 'Estado de Mexico'), ('GTO', 'Guanajuato'), ('GRO', 'Guerrero'), ('HGO', 'Hidalgo'), ('JAL', 'Jalisco'), ('MICH', 'Michoacan'), ('MOR', 'Morelos'), ('NAY', 'Nayarit'), ('NL', 'Nuevo Leon'), ('OAX', 'Oaxaca'), ('PUE', 'Puebla'), ('QRO', 'Queretaro'), ('QROO', 'Quintana Roo'), ('SLP', 'San Luis Potosi'), ('SIN', 'Sinaloa'), ('SON', 'Sonora'), ('TAB', 'Tabasco'), ('TAMS', 'Tamaulipas'), ('TLAX', 'Tlaxcala'), ('VER', 'Veracruz'), ('YUC', 'Yucatan'), ('ZAC', 'Zacatecas')], max_length=5, verbose_name='estado')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('modalidad_interes', models.CharField(choices=[('fijo_capital', 'Interes fijo sobre el capital (tasa x capital)'), ('simple_periodo', 'Interes simple por periodo (tasa x capital x cuotas)'), ('sin_interes', 'Sin interes')], default='fijo_capital', max_length=20, verbose_name='modalidad de interes')),
                ('tasa_interes', models.DecimalField(decimal_places=4, default=Decimal('0.4000'), help_text='Expresada en tanto por uno. 0.4000 = 40% (400 MXN por cada 1,000 MXN).', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='tasa de interes')),
                ('periodo_tasa', models.CharField(choices=[('contrato', 'Por el plazo completo del contrato'), ('diario', 'Por dia'), ('semanal', 'Por semana'), ('quincenal', 'Por quincena'), ('mensual', 'Por mes')], default='contrato', help_text='Periodo contractual al que corresponde la tasa. Debe coincidir con lo pactado en el contrato.', max_length=15, verbose_name='periodo de la tasa')),
                ('frecuencia_pago', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal (cada 15 dias)'), ('mensual', 'Mensual'), ('personalizado', 'Personalizado (cada N dias)')], default='semanal', max_length=15, verbose_name='frecuencia de pago predeterminada')),
                ('numero_cuotas', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)], verbose_name='numero de cuotas predeterminado')),
                ('dias_gracia', models.PositiveIntegerField(default=0, help_text='Dias posteriores al vencimiento antes de considerar la cuota vencida.', verbose_name='dias de gracia')),
                ('aplica_mora', models.BooleanField(default=False, help_text='Si esta desactivado, el sistema NO genera cargos por atraso. Actívalo solo con una politica documentada y autorizada.', verbose_name='aplica cargo moratorio')),
                ('tasa_mora', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tanto por uno sobre el saldo vencido, por dia de atraso.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='tasa moratoria diaria')),
                ('permite_liquidacion_anticipada', models.BooleanField(default=True, verbose_name='permite liquidacion anticipada')),
                ('descuento_liquidacion_anticipada', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Tanto por uno de descuento sobre el interes NO devengado. 0 = se cobra el total contractual.', max_digits=7, verbose_name='descuento por liquidacion anticipada')),
                ('observaciones', models.TextField(blank=True, verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'negocio',
                'verbose_name_plural': 'negocios',
                'ordering': ['nombre_comercial'],
            },
        ),
    ]
