# Generated by Django 5.1.15 on 2026-09-22 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('negocios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='negocios_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='responsable'),
        ),
        migrations.AddConstraint(
            model_name='negocio',
            constraint=models.CheckConstraint(condition=models.Q(('tasa_interes__gte', 0)), name='negocio_tasa_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='negocio',
            constraint=models.CheckConstraint(condition=models.Q(('numero_cuotas__gte', 1)), name='negocio_cuotas_min_1'),
        ),
    ]
