# Generated by Django 5.1.15 on 2026-09-23 06:13

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='installment number')),
                ('due_date', models.DateField(db_index=True, verbose_name='due date')),
                ('scheduled_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='scheduled amount')),
                ('scheduled_principal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='scheduled principal')),
                ('scheduled_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='scheduled interest')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='amount paid')),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='principal paid')),
                ('interest_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='interest paid')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=12, verbose_name='status')),
                ('settled_on', models.DateField(blank=True, null=True, verbose_name='settled on')),
            ],
            options={
                'verbose_name': 'installment',
                'verbose_name_plural': 'installments',
                'ordering': ['loan', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='reference')),
                ('application_date', models.DateField(verbose_name='application date')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='approval date')),
                ('disbursement_date', models.DateField(blank=True, null=True, verbose_name='disbursement date')),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='principal')),
                ('interest_mode', models.CharField(choices=[('flat_on_principal', 'Flat interest on principal (rate x principal)'), ('simple_per_period', 'Simple interest per period (rate x principal x installments)'), ('no_interest', 'No interest')], default='flat_on_principal', max_length=20, verbose_name='interest mode')),
                ('interest_rate', models.DecimalField(decimal_places=4, default=Decimal('0.4000'), help_text='Ratio frozen when the loan was approved.', max_digits=7, verbose_name='applied interest rate')),
                ('rate_period', models.CharField(choices=[('contract', 'For the whole contract term'), ('daily', 'Per day'), ('weekly', 'Per week'), ('biweekly', 'Per fortnight'), ('monthly', 'Per month')], default='contract', max_length=15, verbose_name='rate period')),
                ('total_interest', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total interest')),
                ('total_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total payable')),
                ('payment_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly (every 15 days)'), ('monthly', 'Monthly'), ('custom', 'Custom (every N days)')], default='weekly', max_length=15, verbose_name='payment frequency')),
                ('custom_days', models.PositiveIntegerField(blank=True, help_text='Only for the custom frequency.', null=True, verbose_name='days between installments')),
                ('installment_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of installments')),
                ('installment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='installment amount')),
                ('first_payment_date', models.DateField(verbose_name='first payment date')),
                ('final_due_date', models.DateField(blank=True, null=True, verbose_name='final due date')),
                ('principal_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='principal paid')),
                ('interest_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='interest paid')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='outstanding balance')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('past_due', 'Past due'), ('settled', 'Settled'), ('cancelled', 'Cancelled'), ('restructured', 'Restructured')], db_index=True, default='draft', max_length=25, verbose_name='status')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='cancellation reason')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('contract', models.FileField(blank=True, null=True, upload_to='contracts/%Y/%m/', verbose_name='contract or document')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ['-application_date', '-id'],
            },
        ),
    ]
