# Generated by Django 5.1.15 on 2026-09-23 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0002_initial'),
        ('customers', '0002_initial'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL, verbose_name='approved by'),
        ),
        migrations.AddField(
            model_name='loan',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='businesses.business', verbose_name='business'),
        ),
        migrations.AddField(
            model_name='loan',
            name='collector',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'collector'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_loans', to=settings.AUTH_USER_MODEL, verbose_name='assigned collector'),
        ),
        migrations.AddField(
            model_name='loan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='loan',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='customers.customer', verbose_name='customer'),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to=settings.AUTH_USER_MODEL, verbose_name='disbursed by'),
        ),
        migrations.AddField(
            model_name='loan',
            name='original_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restructurings', to='loans.loan', verbose_name='restructured loan'),
        ),
        migrations.AddField(
            model_name='loan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddField(
            model_name='installment',
            name='loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='loans.loan', verbose_name='loan'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['business', 'status'], name='loans_loan_busines_ad6800_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['customer', 'status'], name='loans_loan_custome_9efb67_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['collector', 'status'], name='loans_loan_collect_4f88f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('principal__gt', 0)), name='loan_principal_positive'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('total_interest__gte', 0)), name='loan_interest_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('installment_count__gte', 1)), name='loan_min_one_installment'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('outstanding_balance__gte', 0)), name='loan_balance_not_negative'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('loan', 'number'), name='installment_number_unique_per_loan'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('scheduled_amount__gte', 0)), name='installment_amount_not_negative'),
        ),
    ]
