# Generated by Django 5.1.15 on 2026-09-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date')),
                ('action', models.CharField(choices=[('create', 'Creation'), ('update', 'Update'), ('deactivate', 'Deactivation'), ('approve', 'Approval'), ('disburse', 'Disbursement'), ('cancel', 'Cancellation'), ('restructure', 'Restructuring'), ('payment', 'Payment registered'), ('reversal', 'Payment reversal'), ('collection', 'Collection action'), ('sign_in', 'System access'), ('export', 'Data export')], max_length=20, verbose_name='action')),
                ('model_name', models.CharField(blank=True, max_length=60, verbose_name='model')),
                ('object_id', models.CharField(blank=True, max_length=40, verbose_name='object id')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log',
                'ordering': ['-created_at'],
            },
        ),
    ]
