"""Catalog of the states of Mexico."""
MEXICAN_STATES = [
    ("AGS", "Aguascalientes"),
    ("BC", "Baja California"),
    ("BCS", "Baja California Sur"),
    ("CAMP", "Campeche"),
    ("CHIS", "Chiapas"),
    ("CHIH", "Chihuahua"),
    ("CDMX", "Ciudad de Mexico"),
    ("COAH", "Coahuila"),
    ("COL", "Colima"),
    ("DGO", "Durango"),
    ("MEX", "Estado de Mexico"),
    ("GTO", "Guanajuato"),
    ("GRO", "Guerrero"),
    ("HGO", "Hidalgo"),
    ("JAL", "Jalisco"),
    ("MICH", "Michoacan"),
    ("MOR", "Morelos"),
    ("NAY", "Nayarit"),
    ("NL", "Nuevo Leon"),
    ("OAX", "Oaxaca"),
    ("PUE", "Puebla"),
    ("QRO", "Queretaro"),
    ("QROO", "Quintana Roo"),
    ("SLP", "San Luis Potosi"),
    ("SIN", "Sinaloa"),
    ("SON", "Sonora"),
    ("TAB", "Tabasco"),
    ("TAMS", "Tamaulipas"),
    ("TLAX", "Tlaxcala"),
    ("VER", "Veracruz"),
    ("YUC", "Yucatan"),
    ("ZAC", "Zacatecas"),
]
