# Generated by Django 5.1.15 on 2026-09-23 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('info', 'Informational'), ('alert', 'Alert'), ('past_due', 'Past due')], default='info', max_length=10, verbose_name='kind')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='link')),
                ('is_read', models.BooleanField(default=False, verbose_name='read')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='businesses.business', verbose_name='business')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
