# Generated by Django 5.1.15 on 2026-09-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='fecha')),
                ('accion', models.CharField(choices=[('crear', 'Creacion'), ('editar', 'Edicion'), ('desactivar', 'Desactivacion'), ('aprobar', 'Aprobacion'), ('desembolsar', 'Desembolso'), ('cancelar', 'Cancelacion'), ('reestructurar', 'Reestructuracion'), ('pago', 'Registro de pago'), ('reverso', 'Reverso de pago'), ('gestion', 'Gestion de cobranza'), ('acceso', 'Acceso al sistema'), ('exportar', 'Exportacion de datos')], max_length=20, verbose_name='accion')),
                ('modelo', models.CharField(blank=True, max_length=60, verbose_name='modelo')),
                ('objeto_id', models.CharField(blank=True, max_length=40, verbose_name='id del objeto')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('datos', models.JSONField(blank=True, default=dict, verbose_name='datos')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-fecha'],
            },
        ),
    ]
